version: '3.8'
services:
  api:
    container_name: api
    restart: always
    build: .
    ports:
      - 3000:3000
    depends_on:
      - db
    command: npm start
    environment:
      - DB_URL=postgres://user:password@postgres/lookup

  db:
    container_name: postgres
    image: postgres:14.1-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./postgres:/data/postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=lookup

